name: Feature Request
description: 用於提出新功能或改進建議。
labels: ['enhancement']

fields:
  - type: input
    label: 功能標題
    description: 請簡要描述您希望的功能
    required: true

  - type: textarea
    label: 描述
    description: 請詳細描述您希望該功能如何運作
    required: true

  - type: textarea
    label: 其他背景或細節
    description: 請提供其他有關這個功能的詳細背景信息
    required: false
